CONTAINER quick_stitch
{
    NAME quick_stitch;
    INCLUDE Obase;

    GROUP ID_OBJECTPROPERTIES
    {
        BUTTON QUICK_STITCH_BUTTON      {}
        LINK   QUICK_STITCH_SOURCE      {}
        LONG   QUICK_STITCH_COUNT       { MIN 0; STEP 1; MINSLIDER 1; MAXSLIDER 200; CUSTOMGUI LONGSLIDER; SCALE_H; }
        //REAL   QUICK_STITCH_STEP        { UNIT METER; }
        REAL   QUICK_STITCH_WIDTH       { UNIT METER; }
        REAL   QUICK_STITCH_HEIGHT      { UNIT METER; }
        REAL   QUICK_STITCH_THICKNESS   { UNIT METER; }
        REAL   QUICK_STITCH_ROTATION    { UNIT DEGREE; MIN 0; MAX 360; CUSTOMGUI REALSLIDER; SCALE_H; }
        REAL   QUICK_STITCH_OFFSET      { UNIT METER; }
        SPLINE QUICK_STITCH_SHAPE       {}
    }
}
