#ifndef _QUICK_STITCH_H_
#define _QUICK_STITCH_H_

enum
{
    QUICK_STITCH_SOURCE     = 1000,
    QUICK_STITCH_STEP       = 1001,
    QUICK_STITCH_COUNT      = 1002,
    QUICK_STITCH_WIDTH      = 1003,
    QUICK_STITCH_HEIGHT     = 1004,
    QUICK_STITCH_THICKNESS  = 1005,
    QUICK_STITCH_OFFSET     = 1006,
    QUICK_STITCH_SHAPE      = 1007,
    QUICK_STITCH_BUTTON     = 1008,
    QUICK_STITCH_ROTATION   = 1009,
    QUICK_STITCH_ROTATION_P = 1010
};

#endif